export const MIN_RETAINED_NEAR_AMOUNT = 0.2;
export const POOL_REFRESH_INTERVAL = 20 * 1000;
export const INIT_SLIPPAGE_VALUE = "0.5";
export const DEFAULT_PAGE_LIMIT = 500;
export const TOP_POOLS_TOKEN_REFRESH_INTERVAL = 60;
export const FEE_DIVISOR = 10000;
export const STABLE_LP_TOKEN_DECIMALS = 18;
export const RATED_POOL_LP_TOKEN_DECIMALS = 24;
